<a href="https://colab.research.google.com/github/kartiksharma2383/Python-Pandas/blob/main/Filtering_the_data%2C_Indexes_in_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd

In [6]:
df = pd.read_csv(r'/content/world_population(Python-Pandas dataset 5).csv')
df

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
230,172,ESH,Western Sahara,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
231,46,YEM,Yemen,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [7]:
#Filtering the data
df[df['Rank'] < 10]

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
16,8,BGD,Bangladesh,Dhaka,Asia,1.711864e+08,1.674210e+08,1.578300e+08,1.483911e+08,1.291933e+08,1.071477e+08,83929765.0,67541860.0,147570.0,1160.0350,1.0108,2.15
27,7,BRA,Brazil,Brasilia,South America,2.153135e+08,2.131963e+08,2.051882e+08,1.963535e+08,1.758737e+08,1.507064e+08,122288383.0,96369875.0,8515767.0,25.2841,1.0046,2.70
41,1,CHN,China,Beijing,Asia,1.425887e+09,1.424930e+09,1.393715e+09,1.348191e+09,1.264099e+09,1.153704e+09,982372466.0,822534450.0,9706961.0,146.8933,1.0000,17.88
92,2,IND,India,New Delhi,Asia,1.417173e+09,1.396387e+09,1.322867e+09,1.240614e+09,1.059634e+09,NaN,NaN,557501301.0,3287590.0,431.0675,1.0068,17.77
93,4,IDN,Indonesia,Jakarta,Asia,2.755013e+08,2.718580e+08,2.590920e+08,2.440162e+08,2.140724e+08,1.821599e+08,148177096.0,115228394.0,1904569.0,144.6529,1.0064,3.45
149,6,NGA,Nigeria,Abuja,Africa,2.185412e+08,2.083274e+08,1.839958e+08,1.609529e+08,1.228520e+08,9.521426e+07,72951439.0,55569264.0,923768.0,236.5759,1.0241,2.74
156,5,PAK,Pakistan,Islamabad,Asia,2.358249e+08,2.271967e+08,2.109693e+08,1.944545e+08,1.543699e+08,1.154141e+08,80624057.0,59290872.0,881912.0,267.4018,1.0191,2.96
171,9,RUS,Russia,Moscow,Europe,1.447133e+08,1.456173e+08,1.446684e+08,1.432426e+08,1.468448e+08,1.480057e+08,138257420.0,130093010.0,17098242.0,8.4636,0.9973,1.81
221,3,USA,United States,"Washington, D.C.",North America,3.382899e+08,3.359420e+08,3.246078e+08,3.111828e+08,2.823986e+08,2.480837e+08,223140018.0,200328340.0,9372610.0,36.0935,1.0038,4.24

In [8]:
specific_countries = ['Bangladesh', 'Brazil']
df[df['Country'].isin(specific_countries)]

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
16,8,BGD,Bangladesh,Dhaka,Asia,171186372.0,167420951.0,157830000.0,148391139.0,129193327.0,107147651.0,83929765.0,67541860.0,147570.0,1160.0350,1.0108,2.15
27,7,BRA,Brazil,Brasilia,South America,215313498.0,213196304.0,205188205.0,196353492.0,175873720.0,150706446.0,122288383.0,96369875.0,8515767.0,25.2841,1.0046,2.70

In [9]:
df[df['Country'].str.contains('United')]

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
219,97,ARE,United Arab Emirates,Abu Dhabi,Asia,9441129.0,9287289.0,8916899.0,8481771.0,3275333.0,1900151.0,1014048.0,298084.0,83600.0,112.9322,1.0081,0.12
220,21,GBR,United Kingdom,London,Europe,67508936.0,67059474.0,65224364.0,62760039.0,58850043.0,57210442.0,56326328.0,55650166.0,242900.0,277.9289,1.0034,0.85
221,3,USA,United States,"Washington, D.C.",North America,338289857.0,335942003.0,324607776.0,311182845.0,282398554.0,248083732.0,223140018.0,200328340.0,9372610.0,36.0935,1.0038,4.24
222,200,VIR,United States Virgin Islands,Charlotte Amalie,North America,99465.0,100442.0,102803.0,106142.0,108185.0,100685.0,96640.0,63446.0,347.0,286.6427,0.9937,0.00

In [10]:
df2 = df.set_index('Country')
df2

,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,,
Afghanistan,36,AFG,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
Albania,138,ALB,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
Algeria,34,DZA,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
American Samoa,213,ASM,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
Andorra,203,AND,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wallis and Futuna,226,WLF,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
Western Sahara,172,ESH,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
Yemen,46,YEM,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
Zambia,63,ZMB,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
Zimbabwe,74,ZWE,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [11]:
df2.filter(items = ['Continent', 'CCA3'], axis = 1)

                  Continent CCA3
Country
Afghanistan            Asia  AFG
Albania              Europe  ALB
Algeria              Africa  DZA
American Samoa      Oceania  ASM
Andorra              Europe  AND
...                     ...  ...
Wallis and Futuna   Oceania  WLF
Western Sahara       Africa  ESH
Yemen                  Asia  YEM
Zambia               Africa  ZMB
Zimbabwe             Africa  ZWE

[234 rows x 2 columns]

In [12]:
df2.filter(items = ['Zimbabwe'], axis = 0)

,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Zimbabwe,74,ZWE,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.2

In [13]:
df2.filter(like = 'United', axis = 0)

,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,,
United Arab Emirates,97,ARE,Abu Dhabi,Asia,9441129.0,9287289.0,8916899.0,8481771.0,3275333.0,1900151.0,1014048.0,298084.0,83600.0,112.9322,1.0081,0.12
United Kingdom,21,GBR,London,Europe,67508936.0,67059474.0,65224364.0,62760039.0,58850043.0,57210442.0,56326328.0,55650166.0,242900.0,277.9289,1.0034,0.85
United States,3,USA,"Washington, D.C.",North America,338289857.0,335942003.0,324607776.0,311182845.0,282398554.0,248083732.0,223140018.0,200328340.0,9372610.0,36.0935,1.0038,4.24
United States Virgin Islands,200,VIR,Charlotte Amalie,North America,99465.0,100442.0,102803.0,106142.0,108185.0,100685.0,96640.0,63446.0,347.0,286.6427,0.9937,0.00

In [14]:
df2.loc['United States']

Rank                                          3
CCA3                                        USA
Capital                        Washington, D.C.
Continent                         North America
2022 Population                     338289857.0
2020 Population                     335942003.0
2015 Population                     324607776.0
2010 Population                     311182845.0
2000 Population                     282398554.0
1990 Population                     248083732.0
1980 Population                     223140018.0
1970 Population                     200328340.0
Area (km²)                            9372610.0
Density (per km²)                       36.0935
Growth Rate                              1.0038
World Population Percentage                4.24
Name: United States, dtype: object

In [15]:
df2.iloc[3]

Rank                                 213
CCA3                                 ASM
Capital                        Pago Pago
Continent                        Oceania
2022 Population                  44273.0
2020 Population                  46189.0
2015 Population                  51368.0
2010 Population                  54849.0
2000 Population                  58230.0
1990 Population                  47818.0
1980 Population                  32886.0
1970 Population                  27075.0
Area (km²)                         199.0
Density (per km²)               222.4774
Growth Rate                       0.9831
World Population Percentage          0.0
Name: American Samoa, dtype: object

In [16]:
#Order By
df[df['Rank'] < 10].sort_values(by=['Rank', 'Country'], ascending = True)

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
41,1,CHN,China,Beijing,Asia,1.425887e+09,1.424930e+09,1.393715e+09,1.348191e+09,1.264099e+09,1.153704e+09,982372466.0,822534450.0,9706961.0,146.8933,1.0000,17.88
92,2,IND,India,New Delhi,Asia,1.417173e+09,1.396387e+09,1.322867e+09,1.240614e+09,1.059634e+09,NaN,NaN,557501301.0,3287590.0,431.0675,1.0068,17.77
221,3,USA,United States,"Washington, D.C.",North America,3.382899e+08,3.359420e+08,3.246078e+08,3.111828e+08,2.823986e+08,2.480837e+08,223140018.0,200328340.0,9372610.0,36.0935,1.0038,4.24
93,4,IDN,Indonesia,Jakarta,Asia,2.755013e+08,2.718580e+08,2.590920e+08,2.440162e+08,2.140724e+08,1.821599e+08,148177096.0,115228394.0,1904569.0,144.6529,1.0064,3.45
156,5,PAK,Pakistan,Islamabad,Asia,2.358249e+08,2.271967e+08,2.109693e+08,1.944545e+08,1.543699e+08,1.154141e+08,80624057.0,59290872.0,881912.0,267.4018,1.0191,2.96
149,6,NGA,Nigeria,Abuja,Africa,2.185412e+08,2.083274e+08,1.839958e+08,1.609529e+08,1.228520e+08,9.521426e+07,72951439.0,55569264.0,923768.0,236.5759,1.0241,2.74
27,7,BRA,Brazil,Brasilia,South America,2.153135e+08,2.131963e+08,2.051882e+08,1.963535e+08,1.758737e+08,1.507064e+08,122288383.0,96369875.0,8515767.0,25.2841,1.0046,2.70
16,8,BGD,Bangladesh,Dhaka,Asia,1.711864e+08,1.674210e+08,1.578300e+08,1.483911e+08,1.291933e+08,1.071477e+08,83929765.0,67541860.0,147570.0,1160.0350,1.0108,2.15
171,9,RUS,Russia,Moscow,Europe,1.447133e+08,1.456173e+08,1.446684e+08,1.432426e+08,1.468448e+08,1.480057e+08,138257420.0,130093010.0,17098242.0,8.4636,0.9973,1.81

In [17]:
df[df['Rank'] < 10].sort_values(by=['Rank', 'Country'], ascending = False)

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
171,9,RUS,Russia,Moscow,Europe,1.447133e+08,1.456173e+08,1.446684e+08,1.432426e+08,1.468448e+08,1.480057e+08,138257420.0,130093010.0,17098242.0,8.4636,0.9973,1.81
16,8,BGD,Bangladesh,Dhaka,Asia,1.711864e+08,1.674210e+08,1.578300e+08,1.483911e+08,1.291933e+08,1.071477e+08,83929765.0,67541860.0,147570.0,1160.0350,1.0108,2.15
27,7,BRA,Brazil,Brasilia,South America,2.153135e+08,2.131963e+08,2.051882e+08,1.963535e+08,1.758737e+08,1.507064e+08,122288383.0,96369875.0,8515767.0,25.2841,1.0046,2.70
149,6,NGA,Nigeria,Abuja,Africa,2.185412e+08,2.083274e+08,1.839958e+08,1.609529e+08,1.228520e+08,9.521426e+07,72951439.0,55569264.0,923768.0,236.5759,1.0241,2.74
156,5,PAK,Pakistan,Islamabad,Asia,2.358249e+08,2.271967e+08,2.109693e+08,1.944545e+08,1.543699e+08,1.154141e+08,80624057.0,59290872.0,881912.0,267.4018,1.0191,2.96
93,4,IDN,Indonesia,Jakarta,Asia,2.755013e+08,2.718580e+08,2.590920e+08,2.440162e+08,2.140724e+08,1.821599e+08,148177096.0,115228394.0,1904569.0,144.6529,1.0064,3.45
221,3,USA,United States,"Washington, D.C.",North America,3.382899e+08,3.359420e+08,3.246078e+08,3.111828e+08,2.823986e+08,2.480837e+08,223140018.0,200328340.0,9372610.0,36.0935,1.0038,4.24
92,2,IND,India,New Delhi,Asia,1.417173e+09,1.396387e+09,1.322867e+09,1.240614e+09,1.059634e+09,NaN,NaN,557501301.0,3287590.0,431.0675,1.0068,17.77
41,1,CHN,China,Beijing,Asia,1.425887e+09,1.424930e+09,1.393715e+09,1.348191e+09,1.264099e+09,1.153704e+09,982372466.0,822534450.0,9706961.0,146.8933,1.0000,17.88

In [18]:
df[df['Rank'] < 10].sort_values(by=['Continent', 'Country'], ascending = [False, True])

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
27,7,BRA,Brazil,Brasilia,South America,2.153135e+08,2.131963e+08,2.051882e+08,1.963535e+08,1.758737e+08,1.507064e+08,122288383.0,96369875.0,8515767.0,25.2841,1.0046,2.70
221,3,USA,United States,"Washington, D.C.",North America,3.382899e+08,3.359420e+08,3.246078e+08,3.111828e+08,2.823986e+08,2.480837e+08,223140018.0,200328340.0,9372610.0,36.0935,1.0038,4.24
171,9,RUS,Russia,Moscow,Europe,1.447133e+08,1.456173e+08,1.446684e+08,1.432426e+08,1.468448e+08,1.480057e+08,138257420.0,130093010.0,17098242.0,8.4636,0.9973,1.81
16,8,BGD,Bangladesh,Dhaka,Asia,1.711864e+08,1.674210e+08,1.578300e+08,1.483911e+08,1.291933e+08,1.071477e+08,83929765.0,67541860.0,147570.0,1160.0350,1.0108,2.15
41,1,CHN,China,Beijing,Asia,1.425887e+09,1.424930e+09,1.393715e+09,1.348191e+09,1.264099e+09,1.153704e+09,982372466.0,822534450.0,9706961.0,146.8933,1.0000,17.88
92,2,IND,India,New Delhi,Asia,1.417173e+09,1.396387e+09,1.322867e+09,1.240614e+09,1.059634e+09,NaN,NaN,557501301.0,3287590.0,431.0675,1.0068,17.77
93,4,IDN,Indonesia,Jakarta,Asia,2.755013e+08,2.718580e+08,2.590920e+08,2.440162e+08,2.140724e+08,1.821599e+08,148177096.0,115228394.0,1904569.0,144.6529,1.0064,3.45
156,5,PAK,Pakistan,Islamabad,Asia,2.358249e+08,2.271967e+08,2.109693e+08,1.944545e+08,1.543699e+08,1.154141e+08,80624057.0,59290872.0,881912.0,267.4018,1.0191,2.96
149,6,NGA,Nigeria,Abuja,Africa,2.185412e+08,2.083274e+08,1.839958e+08,1.609529e+08,1.228520e+08,9.521426e+07,72951439.0,55569264.0,923768.0,236.5759,1.0241,2.74

In [20]:
#Indexing
df = pd.read_csv(r'/content/world_population(Python-Pandas dataset 5).csv', index_col = "Country")
df

,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,,
Afghanistan,36,AFG,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
Albania,138,ALB,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
Algeria,34,DZA,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
American Samoa,213,ASM,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
Andorra,203,AND,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wallis and Futuna,226,WLF,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
Western Sahara,172,ESH,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
Yemen,46,YEM,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
Zambia,63,ZMB,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
Zimbabwe,74,ZWE,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [21]:
df.reset_index(inplace = True)
df

,Country,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,Afghanistan,36,AFG,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,Albania,138,ALB,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,Algeria,34,DZA,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,American Samoa,213,ASM,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,Andorra,203,AND,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,Wallis and Futuna,226,WLF,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
230,Western Sahara,172,ESH,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
231,Yemen,46,YEM,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
232,Zambia,63,ZMB,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
233,Zimbabwe,74,ZWE,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [23]:
df.set_index('Country', inplace = True)
df

,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,,
Afghanistan,36,AFG,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
Albania,138,ALB,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
Algeria,34,DZA,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
American Samoa,213,ASM,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
Andorra,203,AND,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wallis and Futuna,226,WLF,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
Western Sahara,172,ESH,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
Yemen,46,YEM,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
Zambia,63,ZMB,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
Zimbabwe,74,ZWE,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [24]:
df.loc['Albania']

Rank                                 138
CCA3                                 ALB
Capital                           Tirana
Continent                         Europe
2022 Population                2842321.0
2020 Population                2866849.0
2015 Population                2882481.0
2010 Population                2913399.0
2000 Population                3182021.0
1990 Population                3295066.0
1980 Population                2941651.0
1970 Population                2324731.0
Area (km²)                       28748.0
Density (per km²)                98.8702
Growth Rate                       0.9957
World Population Percentage         0.04
Name: Albania, dtype: object

In [25]:
df.iloc[1]

Rank                                 138
CCA3                                 ALB
Capital                           Tirana
Continent                         Europe
2022 Population                2842321.0
2020 Population                2866849.0
2015 Population                2882481.0
2010 Population                2913399.0
2000 Population                3182021.0
1990 Population                3295066.0
1980 Population                2941651.0
1970 Population                2324731.0
Area (km²)                       28748.0
Density (per km²)                98.8702
Growth Rate                       0.9957
World Population Percentage         0.04
Name: Albania, dtype: object

In [26]:
df.reset_index(inplace = True)
df.set_index(['Continent','Country'], inplace = True)
df

                             Rank CCA3           Capital  2022 Population  \
Continent Country
Asia      Afghanistan          36  AFG             Kabul       41128771.0
Europe    Albania             138  ALB            Tirana        2842321.0
Africa    Algeria              34  DZA           Algiers       44903225.0
Oceania   American Samoa      213  ASM         Pago Pago          44273.0
Europe    Andorra             203  AND  Andorra la Vella          79824.0
...                           ...  ...               ...              ...
Oceania   Wallis and Futuna   226  WLF          Mata-Utu          11572.0
Africa    Western Sahara      172  ESH          El Aaiún         575986.0
Asia      Yemen                46  YEM             Sanaa       33696614.0
Africa    Zambia               63  ZMB            Lusaka       20017675.0
          Zimbabwe             74  ZWE            Harare       16320537.0

                             2020 Population  2015 Population  \
Continent Country
Asia      Afghanistan             38972230.0       33753499.0
Europe    Albania                  2866849.0        2882481.0
Africa    Algeria                 43451666.0       39543154.0
Oceania   American Samoa             46189.0          51368.0
Europe    Andorra                    77700.0          71746.0
...                                      ...              ...
Oceania   Wallis and Futuna          11655.0          12182.0
Africa    Western Sahara            556048.0         491824.0
Asia      Yemen                   32284046.0       28516545.0
Africa    Zambia                  18927715.0              NaN
          Zimbabwe                15669666.0       14154937.0

                             2010 Population  2000 Population  \
Continent Country
Asia      Afghanistan             28189672.0       19542982.0
Europe    Albania                  2913399.0        3182021.0
Africa    Algeria                 35856344.0       30774621.0
Oceania   American Samoa             54849.0          58230.0
Europe    Andorra                    71519.0          66097.0
...                                      ...              ...
Oceania   Wallis and Futuna          13142.0          14723.0
Africa    Western Sahara            413296.0         270375.0
Asia      Yemen                   24743946.0       18628700.0
Africa    Zambia                  13792086.0        9891136.0
          Zimbabwe                12839771.0       11834676.0

                             1990 Population  1980 Population  \
Continent Country
Asia      Afghanistan             10694796.0       12486631.0
Europe    Albania                  3295066.0        2941651.0
Africa    Algeria                 25518074.0       18739378.0
Oceania   American Samoa             47818.0          32886.0
Europe    Andorra                    53569.0          35611.0
...                                      ...              ...
Oceania   Wallis and Futuna          13454.0          11315.0
Africa    Western Sahara            178529.0         116775.0
Asia      Yemen                   13375121.0        9204938.0
Africa    Zambia                   7686401.0        5720438.0
          Zimbabwe                10113893.0        7049926.0

                             1970 Population  Area (km²)  Density (per km²)  \
Continent Country
Asia      Afghanistan             10752971.0    652230.0            63.0587
Europe    Albania                  2324731.0     28748.0            98.8702
Africa    Algeria                 13795915.0   2381741.0            18.8531
Oceania   American Samoa             27075.0       199.0           222.4774
Europe    Andorra                    19860.0       468.0           170.5641
...                                      ...         ...                ...
Oceania   Wallis and Futuna           9377.0       142.0            81.4930
Africa    Western Sahara             76371.0    266000.0             2.1654
Asia      Yemen                    6843607.0    527968.0            63.8232
Africa    Zambia                   4281671.0    752612.0            26.5976
          Zimbabwe                 5202918.0    390757.0            41.7665

                             Growth Rate  World Population Percentage
Continent Country
Asia      Afghanistan             1.0257                         0.52
Europe    Albania                 0.9957                         0.04
Africa    Algeria                 1.0164                         0.56
Oceania   American Samoa          0.9831                         0.00
Europe    Andorra                 1.0100                         0.00
...                                  ...                          ...
Oceania   Wallis and Futuna       0.9953                         0.00
Africa    Western Sahara          1.0184                         0.01
Asia      Yemen                   1.0217                         0.42
Africa    Zambia                  1.0280                         0.25
          Zimbabwe                1.0204                         0.20

[234 rows x 15 columns]

In [29]:
df.sort_index(ascending = True)

                            Rank CCA3      Capital  2022 Population  \
Continent     Country
Africa        Algeria         34  DZA      Algiers       44903225.0
              Angola          42  AGO       Luanda       35588987.0
              Benin           77  BEN   Porto-Novo       13352864.0
              Botswana       144  BWA     Gaborone        2630296.0
              Burkina Faso    58  BFA  Ouagadougou       22673762.0
...                          ...  ...          ...              ...
South America Paraguay       109  PRY     Asunción        6780744.0
              Peru            44  PER         Lima       34049588.0
              Suriname       170  SUR   Paramaribo         618040.0
              Uruguay        133  URY   Montevideo        3422794.0
              Venezuela       51  VEN      Caracas       28301696.0

                            2020 Population  2015 Population  2010 Population  \
Continent     Country
Africa        Algeria            43451666.0       39543154.0       35856344.0
              Angola             33428485.0       28127721.0       23364185.0
              Benin              12643123.0       10932783.0        9445710.0
              Botswana            2546402.0        2305171.0        2091664.0
              Burkina Faso       21522626.0       18718019.0       16116845.0
...                                     ...              ...              ...
South America Paraguay            6618695.0        6177950.0        5768613.0
              Peru               33304756.0       30711863.0       29229572.0
              Suriname             607065.0         575475.0         546080.0
              Uruguay             3429086.0        3402818.0        3352651.0
              Venezuela          28490453.0       30529716.0       28715022.0

                            2000 Population  1990 Population  1980 Population  \
Continent     Country
Africa        Algeria            30774621.0       25518074.0       18739378.0
              Angola             16394062.0       11828638.0        8330047.0
              Benin               6998023.0        5133419.0        3833939.0
              Botswana            1726985.0        1341474.0         938578.0
              Burkina Faso       11882888.0        9131361.0        6932967.0
...                                     ...              ...              ...
South America Paraguay            5123819.0        4059195.0        3078912.0
              Peru               26654439.0       22109099.0       17492406.0
              Suriname             478998.0         412756.0         375112.0
              Uruguay             3292224.0        3117012.0        2953750.0
              Venezuela                 NaN       19750579.0       15210443.0

                            1970 Population  Area (km²)  Density (per km²)  \
Continent     Country
Africa        Algeria            13795915.0   2381741.0            18.8531
              Angola              6029700.0   1246700.0            28.5466
              Benin               3023443.0    112622.0           118.5635
              Botswana             592244.0    582000.0             4.5194
              Burkina Faso        5611666.0    272967.0            83.0641
...                                     ...         ...                ...
South America Paraguay            2408787.0    406752.0            16.6705
              Peru               13562371.0   1285216.0            26.4933
              Suriname             379918.0    163820.0             3.7727
              Uruguay             2790265.0    181034.0            18.9069
              Venezuela          11355475.0         NaN            30.8820

                            Growth Rate  World Population Percentage
Continent     Country
Africa        Algeria            1.0164                         0.56
              Angola             1.0315                         0.45
              Benin              1.0274                         0.17
              Botswana           1.0162                         0.03
              Burkina Faso       1.0259                         0.28
...                                 ...                          ...
South America Paraguay           1.0115                         0.09
              Peru               1.0099                         0.43
              Suriname           1.0082                         0.01
              Uruguay            0.9990                         0.04
              Venezuela          1.0036                         0.35

[234 rows x 15 columns]

In [30]:
df.sort_index(ascending = False)

                            Rank CCA3      Capital  2022 Population  \
Continent     Country
South America Venezuela       51  VEN      Caracas       28301696.0
              Uruguay        133  URY   Montevideo        3422794.0
              Suriname       170  SUR   Paramaribo         618040.0
              Peru            44  PER         Lima       34049588.0
              Paraguay       109  PRY     Asunción        6780744.0
...                          ...  ...          ...              ...
Africa        Burkina Faso    58  BFA  Ouagadougou       22673762.0
              Botswana       144  BWA     Gaborone        2630296.0
              Benin           77  BEN   Porto-Novo       13352864.0
              Angola          42  AGO       Luanda       35588987.0
              Algeria         34  DZA      Algiers       44903225.0

                            2020 Population  2015 Population  2010 Population  \
Continent     Country
South America Venezuela          28490453.0       30529716.0       28715022.0
              Uruguay             3429086.0        3402818.0        3352651.0
              Suriname             607065.0         575475.0         546080.0
              Peru               33304756.0       30711863.0       29229572.0
              Paraguay            6618695.0        6177950.0        5768613.0
...                                     ...              ...              ...
Africa        Burkina Faso       21522626.0       18718019.0       16116845.0
              Botswana            2546402.0        2305171.0        2091664.0
              Benin              12643123.0       10932783.0        9445710.0
              Angola             33428485.0       28127721.0       23364185.0
              Algeria            43451666.0       39543154.0       35856344.0

                            2000 Population  1990 Population  1980 Population  \
Continent     Country
South America Venezuela                 NaN       19750579.0       15210443.0
              Uruguay             3292224.0        3117012.0        2953750.0
              Suriname             478998.0         412756.0         375112.0
              Peru               26654439.0       22109099.0       17492406.0
              Paraguay            5123819.0        4059195.0        3078912.0
...                                     ...              ...              ...
Africa        Burkina Faso       11882888.0        9131361.0        6932967.0
              Botswana            1726985.0        1341474.0         938578.0
              Benin               6998023.0        5133419.0        3833939.0
              Angola             16394062.0       11828638.0        8330047.0
              Algeria            30774621.0       25518074.0       18739378.0

                            1970 Population  Area (km²)  Density (per km²)  \
Continent     Country
South America Venezuela          11355475.0         NaN            30.8820
              Uruguay             2790265.0    181034.0            18.9069
              Suriname             379918.0    163820.0             3.7727
              Peru               13562371.0   1285216.0            26.4933
              Paraguay            2408787.0    406752.0            16.6705
...                                     ...         ...                ...
Africa        Burkina Faso        5611666.0    272967.0            83.0641
              Botswana             592244.0    582000.0             4.5194
              Benin               3023443.0    112622.0           118.5635
              Angola              6029700.0   1246700.0            28.5466
              Algeria            13795915.0   2381741.0            18.8531

                            Growth Rate  World Population Percentage
Continent     Country
South America Venezuela          1.0036                         0.35
              Uruguay            0.9990                         0.04
              Suriname           1.0082                         0.01
              Peru               1.0099                         0.43
              Paraguay           1.0115                         0.09
...                                 ...                          ...
Africa        Burkina Faso       1.0259                         0.28
              Botswana           1.0162                         0.03
              Benin              1.0274                         0.17
              Angola             1.0315                         0.45
              Algeria            1.0164                         0.56

[234 rows x 15 columns]

In [32]:
df.loc['Africa', 'Angola']

Rank                                   42
CCA3                                  AGO
Capital                            Luanda
2022 Population                35588987.0
2020 Population                33428485.0
2015 Population                28127721.0
2010 Population                23364185.0
2000 Population                16394062.0
1990 Population                11828638.0
1980 Population                 8330047.0
1970 Population                 6029700.0
Area (km²)                      1246700.0
Density (per km²)                 28.5466
Growth Rate                        1.0315
World Population Percentage          0.45
Name: (Africa, Angola), dtype: object